{"name": "test_add_product_to_cart", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip", "trace": "setup_browser = None\n\n    @pytest.fixture(scope=\"function\")\n    def login(setup_browser):\n>       app.user_log_in.open() \\\n            .fill_username(user.username) \\\n            .fill_password(user.password) \\\n            .login_button()\n\nconftest.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\sauce_demo_UI_autotests\\model\\pages\\login_page.py:6: in open\n    browser.open('/')\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\entity.py:1154: in open\n    self.config._executor.get_url(relative_or_absolute_url)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\configuration.py:303: in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\configuration.py:218: in get\n    driver = config.driver\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\configuration.py:345: in __get__\n    driver = config.build_driver_strategy(config)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\configuration.py:173: in _build_local_driver_by_name_or_remote_by_url_and_options\n    return {  # type: ignore\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selene\\core\\configuration.py:96: in install_and_build_chrome\n    ChromeDriverManager(chrome_type=ChromeType.GOOGLE).install()\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\webdriver_manager\\chrome.py:39: in install\n    driver_path = self._get_driver_path(self.driver)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\webdriver_manager\\core\\manager.py:30: in _get_driver_path\n    file = self._download_manager.download_file(driver.get_url())\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\webdriver_manager\\core\\download_manager.py:28: in download_file\n    response = self._http_client.get(url)\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\webdriver_manager\\core\\http.py:33: in get\n    self.validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresp = <Response [404]>\n\n    @staticmethod\n    def validate_response(resp: requests.Response):\n        status_code = resp.status_code\n        if status_code == 404:\n>           raise ValueError(f\"There is no such driver by url {resp.url}\")\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/115.0.5790/chromedriver_win32.zip\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\webdriver_manager\\core\\http.py:16: ValueError"}, "start": 1690612403139, "stop": 1690612403139, "uuid": "27556e57-948e-4450-9988-ad774f31d9ee", "historyId": "5f49604ed81b35e667d16c534876c103", "testCaseId": "45712f94275279a0d7954510f493ad53", "fullName": "tests.test_cart_page#test_add_product_to_cart", "labels": [{"name": "feature", "value": "Add Product to Cart"}, {"name": "story", "value": "Verify that users can add items to the cart and the cart updates accordingly."}, {"name": "tag", "value": "web"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_cart_page"}, {"name": "host", "value": "LAPTOP-OFQSKCIR"}, {"name": "thread", "value": "18732-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_cart_page"}]}